### ISSUE TITLE
Feature request: Expose walk function

### ISSUE THREAD

**Issue by zhyon404** [BobuSumisu/aho-corasick#2]
https://github.com/BobuSumisu/aho-corasick/blob/87defef828b4b6933802fbd9cb90200902971f17/trie.go#L18

Can we expose this? It's useful when trying ending search when find some substring.

**Comment by BobuSumisu** [comment]
Fixed in https://github.com/BobuSumisu/aho-corasick/commit/0dfa29664f7a30a6f0cea3db577092bc224108a4 :)
